spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: simon
    password:  Simonlll746936!
    url: jdbc:mysql://47.104.166.57/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 47.104.166.57
    port: 6379
  rabbitmq:
    host: 47.104.166.57
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
server:
  port: 8089
env:
  dev
girl:
  name: zouwangbei
  age: 88
