spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: simon
    password:  Simonlll746936!
    url: jdbc:mysql://hadoop/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8089
env:
  dev
girl:
  name: simonlin
  age: 007
