spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: simon
    password:  Simonlll746936!
    url: jdbc:mysql://47.104.166.57/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 47.104.166.57
    port: 5672
    username: guest
    password: guest
